import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { WishlistProvider } from "@/context/WishListContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Navbar
          links={[
            { href: "/", label: "Home" },
            { href: "/ItemsList", label: "Item List" },
            { href: "/WishList", label: "Wish List" },
            { href: "/AddProduct", label: "Add Product" },
          ]}
        />
        <WishlistProvider>{children}</WishlistProvider>
      </body>
    </html>
  );
}
